{
  "\"TOUT\"": "TOUT",
  "\"HD_PAO\"": "HD_PAO",
  "\"HD_G_FINITION\"": "HD_G_FINITION",
  "\"HD_FORMAT_OUVERT\"": "HD_FORMAT_OUVERT",
  "\"HD_G_TRANSPORT\"": "HD_G_TRANSPORT",
  "\"HD_G_MODEL\"": "HD_G_MODEL",
  "\"HD_PAGE\"": "HD_PAGE",
  "\"HD_G_EMBALLAGE\"": "HD_G_EMBALLAGE",
  "\"HD_G_ASSEMBLAGE\"": "HD_G_ASSEMBLAGE",
  "\"HD_FACONNAGE\"": "HD_FACONNAGE",
  "\"HD_FINITION\"": "HD_FINITION",
  "\"HD_PRINT\"": "HD_PRINT",
  "\"HD_QTE\"": "HD_QTE",
  "\"HD_FORMAT\"": "HD_FORMAT"
}
